language: c++
sudo: required
dist: trusty

os:
  - linux
  # - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

before_script:
  # # OSX dependencies
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5"; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install exiv2; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libraw; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew tap homebrew/science; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install -v opencv3 --with-contrib --without-eigen --without-opencl --without-openexr --without-python --without-tests; fi
  # - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew ln opencv3 --force; fi

  # Linux dependencies
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-add-repository -y ppa:beineri/opt-qt551-trusty; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y --no-install-recommends debhelper cdbs qt5-qmake libqt5core5a libqt5widgets5 libqt5network5 libqt5gui5 libqt5printsupport5 libqt5svg5-dev qttools5-dev-tools qttools5-dev qt5-default libexiv2-dev libraw-dev libopencv-dev libhighgui-dev libcvaux-dev cmake libtiff-dev libzip-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/opt/qt55/bin/ -DENABLE_IMAGESTITCHING=off -DENABLE_QUAZIP=OFF"; fi
  
  - git clone --depth 1 http://github.com/nomacs/nomacs nomacs
  - mkdir -p nomacs/ImageLounge/plugins
  - find . -maxdepth 1 -not -name "nomacs" -not -name ".*" -exec mv {} nomacs/ImageLounge/plugins/ \;
  - mkdir build
  - cd build

script:
  - cmake $CMAKE_ARGS ../nomacs/ImageLounge/.
  - make -j8
 