language: cpp
dist: xenial

os:
  - linux
  # - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    update: true
    packages:
        - cmake
        - build-essential
        - qt5-default
        - qttools5-dev-tools 
        - qttools5-dev
        - libqt5svg5-dev
        - libexiv2-dev
        # optional packages
        - libopencv-dev
        - libraw-dev
        - libquazip5-dev

  # OS X
  homebrew:
    update: true
    packages:
      - qt5
      - opencv3
      - exiv2
      - libraw

before_script:
  # OSX CMake paths
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/usr/local/opt/qt5"; fi

  # Linux CMake paths (here we also test the minimal configuration)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CMAKE_ARGS="-DCMAKE_PREFIX_PATH=/opt/qt55/bin/ -DENABLE_PLUGINS=OFF -DENABLE_QUAZIP=OFF"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then CMAKE_MINIMAL_ARGS="-DCMAKE_PREFIX_PATH=/opt/qt55/bin/ -DENABLE_PLUGINS=OFF -DENABLE_OPENCV=OFF -DENABLE_RAW=OFF -DENABLE_TIFF=OFF -DENABLE_QUAZIP=OFF"; fi
  
  - mkdir build
  - cd build

script:
  - cmake $CMAKE_ARGS ../ImageLounge/.
  - make -j8
  - cmake $CMAKE_MINIMAL_ARGS ../ImageLounge/.
  - make -j8
  
after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # upload report to Codecov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    
notifications:
  email:
    - diemmarkus@gmail.com
